### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Neubivljiv** [PushkinStudio/PsFacebookMobile#10]
Hello,

I got the following error when I try to build game with this plugin:
```
UATHelper: Packaging (Android (ETC2)):     E:/UE4Projects/MobileMenu/Plugins/PsFacebookMobile/Source/PsFacebookMobile/Private/Android/AdjustJNI.h(14,10):  fatal error: 'Android/AndroidJNI.h' file not found
UATHelper: Packaging (Android (ETC2)):     #include "Android/AndroidJNI.h"
```

I am using UE 4.23.1, ndk-r14b, jdk1.8.0_77, android-19
Note: without plugin project compile without problem.
What I am missing?

**Comment by ufna** [comment]
Currently it's definitely supports UE 4.24 and above. Unfortunately UE 4.23 is not supported.

**Comment by Neubivljiv** [comment]
I already tried on 4.24 and it did not work...
I mean I could not start the project because it always shows me the message that project **could not be compiled**. It's working in 4.23 and project started.

**Comment by ufna** [comment]
You should completely disable built-in Facebook (it's enabled by default at Project settings/Android)

**Comment by Neubivljiv** [comment]
Tried to find it. There's only option for iOS "Enable Facebook Support" which is disabled and there is plugin Facebook Online Subsystem which is also disabled.
I can start the project with UE4.23 but can not compile the project and I can not even start the project with UE4.24 because it wont compile this plugin. 
Thanks for reply anyway.

**Comment by ufna** [comment]
Oh, I mixed up with other out plugin. I'll check compilation on clean project today.

**Comment by ufna** [comment]
I've just tested clean project from Topdown template with our plugin enabled, but on UE 4.25. 

Works like a charm. Please check exact compilation issue with UE 4.24.

**Comment by Neubivljiv** [comment]
Thanks.
Just wanted to note that I also tested in 4.25 and it's working great - auth token is returned, everything is perfect.
