### ISSUE TITLE
package error on mac for ios

### ISSUE THREAD

**Issue by vinkumdev** [PushkinStudio/PsFacebookMobile#11]
Hi I am trying to use your plugin but get this error

Plugins/PsFacebookMobile/Source/PsFacebookMobile/Private/IOS/FacebookMobile.cpp:8:9: fatal error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
UATHelper: Packaging (iOS):   #import <FBSDKCoreKit/FBSDKCoreKit.h>
UATHelper: Packaging (iOS):           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Antonrr** [comment]
Hello!

Please update the plugin to the latest version, enable it in project settings, and don't forget to fill in app id.

**Comment by vinkumdev** [comment]
Just wanted to say thank you very much for sharing, It worked smoothly.
