### ISSUE TITLE
Error during iOS build

### ISSUE THREAD

**Issue by vladhoncharenko** [PushkinStudio/PsFacebookMobile#15]
Hi, I have the following error during the iOS build (Compiling with iPhoneOS SDK 14.2):

UATHelper: Packaging (iOS):     ERROR: Unable to merge actions producing FBSDKCoreKit.embeddedframework.extracted: prerequisites are different
UATHelper: Packaging (iOS):     ERROR: Unable to merge actions producing FBSDKLoginKit.embeddedframework.extracted: prerequisites are different
UATHelper: Packaging (iOS):     ERROR: Action graph is invalid; unable to continue. See log for additional details.
PackagingResults: Error: Unable to merge actions producing FBSDKCoreKit.embeddedframework.extracted: prerequisites are different
PackagingResults: Error: Unable to merge actions producing FBSDKLoginKit.embeddedframework.extracted: prerequisites are different
PackagingResults: Error: Action graph is invalid; unable to continue. See log for additional details.

I have the following errors in the log file:
UEDeployIOS.CollectPluginDataPaths: IOSPlugin: ../../../Dev/fallgamedemo/Plugins/PsFacebookMobile/Source/PsFacebookMobile/PsFacebookMobile_UPL_IOS.xml
UEBuildTarget.GenerateManifest: Writing manifest to /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/Dev/fallgamedemo/Intermediate/Remote/GameName/IOS/Shipping/Manifest.xml
Action.LogConflict: ERROR: Unable to merge actions producing FBSDKCoreKit.embeddedframework.extracted: prerequisites are different
Action.LogConflict:   Previous: /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/Dev/fallgamedemo/Plugins/PsFacebookMobile/ThirdParty/FacebookSDKs-iOS/FBSDKCoreKit.embeddedframework.zip, /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/UE/UE_4.25/Engine/Intermediate/UnzippedFrameworks/FBSDKCoreKit/FBSDKCoreKit.embeddedframework.sh
Action.LogConflict:   Conflict: /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/UE/UE_4.25/Engine/Plugins/Marketplace/EasyFirebasePro/Source/ThirdParty/IOS/FBSDKCoreKit.embeddedframework.zip, /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/UE/UE_4.25/Engine/Intermediate/UnzippedFrameworks/FBSDKCoreKit/FBSDKCoreKit.embeddedframework.sh
Action.LogConflict: ERROR: Unable to merge actions producing FBSDKLoginKit.embeddedframework.extracted: prerequisites are different
Action.LogConflict:   Previous: /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/Dev/fallgamedemo/Plugins/PsFacebookMobile/ThirdParty/FacebookSDKs-iOS/FBSDKLoginKit.embeddedframework.zip, /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/UE/UE_4.25/Engine/Intermediate/UnzippedFrameworks/FBSDKLoginKit/FBSDKLoginKit.embeddedframework.sh
Action.LogConflict:   Conflict: /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/UE/UE_4.25/Engine/Plugins/Marketplace/EasyFirebasePro/Source/ThirdParty/IOS/FBSDKLoginKit.embeddedframework.zip, /Users/vlad/UE4/Builds/DESKTOP-DKM1111/D/UE/UE_4.25/Engine/Intermediate/UnzippedFrameworks/FBSDKLoginKit/FBSDKLoginKit.embeddedframework.sh
UnrealBuildTool.Main: ERROR: Action graph is invalid; unable to continue. See log for additional details.
UnrealBuildTool.Main: BuildException: Action graph is invalid; unable to continue. See log for additional details.
UnrealBuildTool.Main:   at UnrealBuildTool.ActionGraph.CheckForConflicts (System.Collections.Generic.IEnumerable`1[T] Actions) [0x0008c] in <4308e3bdfb1844339db4a61e5a2da573>:0 
UnrealBuildTool.Main:   at UnrealBuildTool.BuildMode.Build (System.Collections.Generic.List`1[T] TargetDescriptors, UnrealBuildTool.BuildConfiguration BuildConfiguration, UnrealBuildTool.ISourceFileWorkingSet WorkingSet, UnrealBuildTool.BuildOptions Options, Tools.DotNETCommon.FileReference WriteOutdatedActionsFile) [0x000c6] in <4308e3bdfb1844339db4a61e5a2da573>:0 
UnrealBuildTool.Main:   at UnrealBuildTool.BuildMode.Execute (Tools.DotNETCommon.CommandLineArguments Arguments) [0x00377] in <4308e3bdfb1844339db4a61e5a2da573>:0 
UnrealBuildTool.Main:   at UnrealBuildTool.UnrealBuildTool.Main (System.String[] ArgumentsArray) [0x002bb] in <4308e3bdfb1844339db4a61e5a2da573>:0

Any ideas on this?

**Comment by ufna** [comment]
Hi @vladhoncharenko ,

You should disable built-in Facebook support.

**Comment by vladhoncharenko** [comment]
Hi @ufna,

I disabled built-in Facebook plugin and Facebook iOS support before installing PsFacebookMobile.
I have other plugins that might use the Facebook SDK, could this be a problem?

**Comment by ufna** [comment]
@vladhoncharenko , yes, it's not possible to use plugins that rely on different versions of platform SDK.

**Comment by vladhoncharenko** [comment]
Got it, thanks.
