### ISSUE TITLE
FBAudienceNetwork(FBANInterstitialAdAdapter.m.o): 'Invalid bitcode version

### ISSUE THREAD

**Issue by Jackyuan999** [PushkinStudio/PsFacebookMobile#16]
Hi, sorry to bother you. I use this plugin in UE4.23.1 , when packaging iOS (MacOS 10.14.3, Xcode10.3) , got this error: 
UATHelper: Packaging (iOS):     ld: in /Users/yuanjie/UE4/Builds/DESKTOP-N5JLND9/D/Epic_Games/UE_4.23/Engine/Intermediate/UnzippedFrameworks/FBAudienceNetwork/FBAudienceNetwork.embeddedframework/FBAudienceNetwork.framework/FBAudienceNetwork(FBANInterstitialAdAdapter.m.o), could not parse object file /Users/yuanjie/UE4/Builds/DESKTOP-N5JLND9/D/Epic_Games/UE_4
.23/Engine/Intermediate/UnzippedFrameworks/FBAudienceNetwork/FBAudienceNetwork.embeddedframework/FBAudienceNetwork.framework/FBAudienceNetwork(FBANInterstitialAdAdapter.m.o): 'Invalid bitcode version (Producer: '1103.0.32.59.0_0' Reader: '1001.0.46.4_0')', using libLTO version 'LLVM version 10.0.1, (clang-1001.0.46.4)' file '/Users/yuanjie/UE4/Builds/DESKTOP
-N5JLND9/D/Epic_Games/UE_4.23/Engine/Intermediate/UnzippedFrameworks/FBAudienceNetwork/FBAudienceNetwork.embeddedframework/FBAudienceNetwork.framework/FBAudienceNetwork' for architecture arm64

clang: error: linker command failed with exit code 1
Have you ever seen this error before? thanks a lot!

**Comment by ufna** [comment]
@Jackyuan999 , you should update XCode. I'm not sure it will work with UE 4.23, plugin is designed for UE 4.25/4.26

**Comment by Jackyuan999** [comment]
Thank you very much.
