### ISSUE TITLE
Requesting for Documentation on how to use

### ISSUE THREAD

**Issue by VmukeshK** [PushkinStudio/PsFacebookMobile#33]
Hlo thank u for this amazing plugin,
is it possible to get simple documentation on how to use 
i am testing in editor but the login doesnot work

**Comment by Antonrr** [comment]
Hello!

Unfortunately there's no preview mode for testing in editor, editor implementation just returns empty callbacks.

To login on iOS or Android platform, call `UPsFacebookMobileLibrary::FacebookLogin`. For further info please refer to plugin source code and Facebook SDK documentation.
